name: run-c-tests
on:
  push:
jobs:
  build-and-run-c-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install check library
        run: |
          sudo apt update
          sudo apt install -y check
      - name: Build and run C tests
        run: make ctest
      - name: Build and run library tests
        run: make libtest